title: My blog
owner: Egydio
email:
description: Just my space to write things
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://egydiopacheco.github.io" # the base hostname & protocol for your site, e.g. http://example.com
language: en
twitter_username: Egydio18
github_username: egydiopacheco
disqus_username: 
# Build settings
markdown: kramdown
theme: minima

permalink: /:year/:month/:day/:title/

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle
excerpt_separator: <!--more-->
